<a href="https://colab.research.google.com/github/BestApisit/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลาย ๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

## `list()`
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a=[1,2,3,4,5,6] #[ ] square brackets (วงเล็บเหลี่ยม)

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b=['ab',2,3.14,list_a]

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4] #list_bที่ตำแหน่ง 3 ข้างใน 3 เป็นตำแหน่งที่ 4

5

In [ ]:
list_a[6] # list_a มีตำแหน่ง 0 1 2 3 4 5 ไม่มีตำแหน่ง 6 เลย error

IndexError: ignored

In [ ]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list_a

6

In [ ]:
list_a[-2] #index -2 คือตัวรองสุดท้ายของ list_a

5

### การสร้าง list()

In [ ]:
list_x1=[] #แบบที่ 1
list_x2=list() #แบบที่ 2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย `append()`

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4) #runกี่ครั้งตัวเลขจะขึ้นเท่านั้น ตรงนี้ run 4 2 ครั้ง
print(list_x1)

[2, 4, 4]


In [ ]:
list_x2

[]

In [ ]:
list_x2.append('ha') # run 2 ครั้ง
print(list_x2)

['ha', 'ha']


### ลบสมาชิกจาก list

In [ ]:
list_x1.append('ha')

In [ ]:
list_x1

[2, 4, 4, 'ha']

In [ ]:
list_x1.pop() #pop ลบตัวสุดท้าย 

'ha'

In [ ]:
list_x1

[2, 4, 4]

In [ ]:
list_x1.pop() # run 2 ครั้ง ลบไป 2 ตัว จาก 2,4,4 เหลือ 2
print(list_x1)

[2]


###`len()`ตรวจสอบจำนวนสมาชิก list

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

###String is a list of characters

In [ ]:
st_stat='Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10] #ตรงตำแหน่ง 10 ว่าง

' '

In [ ]:
st_stat[14] #ตรงตำแหน่ง 14 เป็นตัว S

'S'

In [ ]:
len(st_stat) #มีทั้งหมด 44 ตำแหน่ง

44

### List Slicing `:`

`list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]`

`list[จุดเริ่มต้น:จุดสุดท้าย:step]`

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

In [ ]:
list_a[-3:] # : colon

[4, 5, 6]

In [ ]:
list_a[:-4] 

[1, 2]

In [ ]:
list_a[4:] 

[5, 6]

In [ ]:
list_a[-4:] 

[3, 4, 5, 6]

In [ ]:
list_a[:4] 

[1, 2, 3, 4]

In [ ]:
list_a[1:4] 

[2, 3, 4]

####step

In [ ]:
list_c=[1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[10:]

[11, 12, 13]

In [ ]:
list_c[10::2]

[11, 13]

In [ ]:
list_c[1::2]

[2, 4, 6, 8, 10, 12]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

###`range()`

In [ ]:
range(21)

range(0, 21)

In [ ]:
a=list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (printออกมาให้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
#01:02:03
a=1*60*60 +(2*60)+3
print(f'01:02:03 แปลงเป็นวินาที ได้ {a} วินาที') #ตัวอย่าง

01:02:03 แปลงเป็นวินาที ได้ 3723 วินาที


##`HW2`

In [ ]:
#12:30:15
b = '12:30:15'
b1 = b.split(':')
ans =int(b1[0])*60*60 +int(b1[1])*60+int(b1[2])
print(f'No.1) 12:30:15 น. = {ans} วินาที')

No.1) 12:30:15 น. = 45015 วินาที


In [ ]:
#13:41:07
c = '13:41:07'
c1 = c.split(':')
ans =int(c1[0])*60*60 +int(c1[1])*60+int(c1[2])
print(f'No.2) 13:41:07 น. = {ans} วินาที')

No.2) 13:41:07 น. = 49267 วินาที


In [ ]:
#09:11:50
d = '09:11:50'
d1 = d.split(':')
ans =int(d1[0])*60*60 +int(d1[1])*60+int(d1[2])
print(f'No.3) 09:11:50 น. = {ans} วินาที')

No.3) 09:11:50 น. = 33110 วินาที


In [ ]:
#21:30:15
e = '21:30:15'
e1 = e.split(':')
ans =int(e1[0])*60*60 +int(e1[1])*60+int(e1[2])
print(f'No.4) 21:30:15 น. = {ans} วินาที')

No.4) 21:30:15 น. = 77415 วินาที


In [ ]:
#03:10:15
f = '03:10:15'
f1 = f.split(':')
ans =int(f1[0])*60*60 +int(f1[1])*60+int(f1[2])
print(f'No.5) 03:10:15 น. = {ans} วินาที')

No.5) 03:10:15 น. = 11415 วินาที


## Dictionary

- คล้าย list ()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขลำดับ
- ลำดับไม่มีความสำคัญ

###สร้าง Dictionary

In [ ]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly brackets

### การชี้ สมาชิกใน Dictionary

In [ ]:
dict_a[1]

'Happy'

In [ ]:
dict_a['N']

'New'

In [ ]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [ ]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7]=3.14

In [ ]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [ ]:
dict_a['N']='NNNNEEEEWWWW'

In [ ]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

##Numpy Array

- เก็บได้แต่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2 มิติ ก็มองเป็น Matrix)

In [ ]:
import numpy

###1D array

In [ ]:
list_A=[1,2,3,4,5]

In [ ]:
arr_a=numpy.array(list_A)

In [ ]:
arr_a

array([1, 2, 3, 4, 5])

In [ ]:
list_A

[1, 2, 3, 4, 5]

In [ ]:
arr_a[0]

1

In [ ]:
list_A[0]

1

In [ ]:
5*arr_a #Matrix (scalar multiplication) arr มีคุณสมบัติคูณกระจายเข้าไป

array([ 5, 10, 15, 20, 25])

In [ ]:
5*list_A # list เอามาคูณ จะมีตัวเลข 5 รอบ ต่างจาก arr

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
arr_b=numpy.array([10,20,30,40,50])

In [ ]:
print(arr_a)

[1 2 3 4 5]


In [ ]:
arr_a+arr_b #บวก matrix ตัวตำแหน่งเดียวกันบวกกัน

array([11, 22, 33, 44, 55])

In [ ]:
arr2_z.shape

(2, 3)

###2D array

In [ ]:
import numpy as np

In [ ]:
arr2_z=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

###`np.zeros()`

In [ ]:
arr2_3_5_0=np.zeros((3,5))

In [ ]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2_3_5_0[1,2]=9 #กำหนดค่า แถวหนึ่งหลักสองเท่ากับ 9

In [ ]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2_3_5_0[1,2] #ชี้ค่า

9.0

In [ ]:
print(list_A) #เปลี่ยนคำใน list()
list_A[-1]='Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


###`np.ones()`

In [ ]:
arr2_4_5_1=np.ones( (4,5) )

In [ ]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr2_4_5_200=200*np.ones((4,5))

In [ ]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

###Matrix operations

####การบวก ลบ Matrix $M \pm N$ บวกลบตัวที่อยู๋ตำแหน่งเดียวกัน

In [ ]:
arr2_4_5_200+arr2_3_5_0 #การบวก ลบ matrix shape ต้องเท่ากัน

ValueError: ignored

In [ ]:
arr2_4_5_200+arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

####การคูณ matrix

- $aM$ scalar คูณ Matrix (คูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)

In [ ]:
5*arr_a #Matrix (scalar multiplication) arr มีคุณสมบัติคูณกระจายเข้าไป

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)

- (m,n) $\times $ (n,0) = (m,o) (Shape)

In [ ]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6,],[7,9]])

In [ ]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [ ]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [ ]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc

In [ ]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [ ]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [ ]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [ ]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [ ]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [ ]:
mat_a*mat_b #คูณตัวตำแหน่งเดียวกัน ที่จริงไม่มีการคูณที่เท่ากัน

array([[  2,   6,  25],
       [  8,  24, -49]])

###Matrix Slicing

In [ ]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

#HW 3

1. สร้าง array ที่มีรูป ต้น Christmas
2. slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [8]:
HW3=np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
HW3[::4,2]=1
HW3[::4,4]=1
HW3[::4,6]=1
HW3[::4,8]=1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
import numpy as np

In [11]:
Xmas=77*np.ones((28,15))
Xmas[22:,6:9] = 88
Xmas[21:22:] =88
Xmas[20,1:14] = 88
Xmas[19,2:13] = 88
Xmas[18,3:12] = 88
Xmas[17,4:11] = 88
Xmas[16,1:14] = 88
Xmas[15,2:13] = 88
Xmas[14,3:12] = 88
Xmas[13,4:11] = 88
Xmas[12,5:10] = 88
Xmas[11,2:13] = 88
Xmas[10,3:12] = 88
Xmas[9,4:11] = 88
Xmas[8,5:10] = 88
Xmas[7,6:9] = 88
Xmas[6,3:12] = 88
Xmas[5,4:11] = 88
Xmas[4,5:10] = 88
Xmas[3,6:9] = 88
Xmas[2,7:8] = 88
print(Xmas)

[[77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 77. 77. 77. 88. 77. 77. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 77. 77. 88. 88. 88. 77. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 77. 88. 88. 88. 88. 88. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 88. 88. 88. 88. 88. 88. 88. 77. 77. 77. 77.]
 [77. 77. 77. 88. 88. 88. 88. 88. 88. 88. 88. 88. 77. 77. 77.]
 [77. 77. 77. 77. 77. 77. 88. 88. 88. 77. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 77. 88. 88. 88. 88. 88. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 88. 88. 88. 88. 88. 88. 88. 77. 77. 77. 77.]
 [77. 77. 77. 88. 88. 88. 88. 88. 88. 88. 88. 88. 77. 77. 77.]
 [77. 77. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 77. 77.]
 [77. 77. 77. 77. 77. 88. 88. 88. 88. 88. 77. 77. 77. 77. 77.]
 [77. 77. 77. 77. 88. 88. 88. 88. 88. 88. 88. 77. 77. 77. 77.]
 [77. 77. 77. 88. 88. 88. 88. 88. 88. 88. 88. 88. 77. 77. 77.]
 [77. 77. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 88. 7

In [12]:
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##Pandas Dataframe (แยกออกไปเป็น Notebook เฉพาะ)